export {
  addStage,
  deleteStage,
  renameStage,
  addInteraction,
  deleteInteraction,
  renameInteraction,
  addEntryToStage,
  addEntryToRootSlot,
  addRewardSlot,
  renameRewardSlot,
  addEntryToRewardSlot,
  addEntryToInteraction,
  addEntryForSelection,
  addEntryToTarget,
  addEntryToEntrySlot,
  deleteEntry,
  duplicateEntry,
  moveEntry,
  changeEntryType
} from './qxlDocument';
