import { Accordion, Alert, Paper, Stack, TagsInput, Text } from '@mantine/core';
import type { AssetCatalog } from '../../api/types';
import { ValueField } from '../fields/ValueField';

export function HephaestusItemEditor({ data, disabled, assets, onFieldChange }: { data: Record<string, any>; disabled: boolean; assets: AssetCatalog; onFieldChange: (field: string, value: unknown) => void }) {
  const errors = validateHephaestusItem(data, assets);
  return (
    <Stack gap="sm">
      <Text fw={700}>Hephaestus item</Text>
      <ValidationSummary errors={errors} />
      <Paper p="md" withBorder className="slotBox">
        <Stack gap="sm">
          <Text fw={700}>Identity</Text>
          <ValueField label="key" description="Unique item id used by /give and references. Use namespace:path, usually erethon:item_name." error={errors.key} value={data.key} disabled={disabled} onChange={(value) => onFieldChange('key', value)} />
          <ValueField label="baseItem" description="Vanilla item this custom item is based on. Search materials or type a full minecraft id." error={errors.baseItem} value={data.baseItem} kind="material" disabled={disabled} assets={assets} onChange={(value) => onFieldChange('baseItem', value)} />
          <TagsInput
            label="tags"
            description="Searchable/category tags used by UI and filters. Type a tag and press Enter."
            error={errors.tags}
            value={tagList(data.tags)}
            disabled={disabled}
            clearable
            onChange={(value) => onFieldChange('tags', value)}
          />
        </Stack>
      </Paper>
      <Paper p="md" withBorder className="slotBox">
        <Stack gap="sm">
          <Text fw={700}>Localized Text</Text>
          <ValueField label="name.en" description="English display name." error={errors['name.en']} value={data.name?.en} kind="minimessage" disabled={disabled} onChange={(value) => onFieldChange('name.en', value)} />
          <ValueField label="name.de" description="German display name." error={errors['name.de']} value={data.name?.de} kind="minimessage" disabled={disabled} onChange={(value) => onFieldChange('name.de', value)} />
          <ValueField label="category.en" description="English item category shown in item UI." value={data.category?.en} kind="minimessage" disabled={disabled} onChange={(value) => onFieldChange('category.en', value)} />
          <ValueField label="category.de" description="German item category shown in item UI." value={data.category?.de} kind="minimessage" disabled={disabled} onChange={(value) => onFieldChange('category.de', value)} />
          <ValueField label="flavour.en" description="English lore/flavour text." value={data.flavour?.en} kind="minimessage" disabled={disabled} onChange={(value) => onFieldChange('flavour.en', value)} />
          <ValueField label="flavour.de" description="German lore/flavour text." value={data.flavour?.de} kind="minimessage" disabled={disabled} onChange={(value) => onFieldChange('flavour.de', value)} />
        </Stack>
      </Paper>
      <Paper p="md" withBorder className="slotBox">
        <Stack gap="sm">
          <Text fw={700}>Components</Text>
          <ValueField label="patch" description="JSON component patch applied on top of vanilla. Components here override vanilla components." error={errors.patch} value={data.patch} kind="json" disabled={disabled} onChange={(value) => onFieldChange('patch', value)} />
          <Accordion variant="contained">
            <Accordion.Item value="vanilla">
              <Accordion.Control>
                <Text fw={600}>Vanilla snapshot</Text>
                <Text size="xs" c="dimmed">Read-only generated base item JSON.</Text>
              </Accordion.Control>
              <Accordion.Panel>
                <ValueField label="vanilla" description="JSON component snapshot from the base item. Usually generated by Hephaestus." error={errors.vanilla} value={data.vanilla} kind="json" disabled onChange={() => undefined} />
              </Accordion.Panel>
            </Accordion.Item>
          </Accordion>
          <ValueField label="random" description="YAML map for level, rarity, socket pattern, and other randomization weights." error={errors.random} value={data.random || {}} kind="raw" disabled={disabled} onChange={(value) => onFieldChange('random', value)} />
        </Stack>
      </Paper>
    </Stack>
  );
}

function tagList(value: unknown) {
  if (Array.isArray(value)) return value.map(String).map((tag) => tag.trim()).filter(Boolean);
  return String(value ?? '').split(',').map((tag) => tag.trim()).filter(Boolean);
}

function validateHephaestusItem(data: Record<string, any>, assets: AssetCatalog) {
  const errors: Record<string, string> = {};
  const key = String(data.key || '').trim();
  if (!key) errors.key = 'Required. Use namespace:path.';
  else if (!/^[a-z0-9_.-]+:[a-z0-9_./-]+$/.test(key)) errors.key = 'Use lowercase namespace:path, for example erethon:iron_key.';
  const baseItem = String(data.baseItem || '').trim();
  if (!baseItem) errors.baseItem = 'Required. Use a valid minecraft item id.';
  else if (assets.materials.length > 0 && !assets.materials.some((item) => item.id === baseItem)) errors.baseItem = 'Not found in the live material list. You can still type manually if this is intentional.';
  if (!String(data.name?.en || '').trim()) errors['name.en'] = 'Recommended. English display names are used as the fallback.';
  if (!String(data.name?.de || '').trim()) errors['name.de'] = 'Recommended for German player-facing content.';
  if (data.tags != null && !Array.isArray(data.tags)) errors.tags = 'Tags should be a YAML list of strings.';
  if (Array.isArray(data.tags) && data.tags.some((tag) => typeof tag !== 'string')) errors.tags = 'Every tag should be text.';
  if (data.vanilla && !isJson(data.vanilla)) errors.vanilla = 'Must be valid JSON.';
  if (data.patch && !isJson(data.patch)) errors.patch = 'Must be valid JSON.';
  if (data.random != null && !isPlainObject(data.random)) errors.random = 'Randomization should be a YAML map.';
  return errors;
}

function ValidationSummary({ errors }: { errors: Record<string, string> }) {
  const values = Object.entries(errors);
  if (values.length === 0) return <Alert color="green" variant="light">No issues detected.</Alert>;
  return (
    <Alert color="red" variant="light" title={`${values.length} issue${values.length === 1 ? '' : 's'}`}>
      <Stack gap={2}>{values.map(([field, message]) => <Text key={field} size="sm"><b>{field}</b>: {message}</Text>)}</Stack>
    </Alert>
  );
}

function isJson(value: unknown) {
  try {
    JSON.parse(String(value));
    return true;
  } catch {
    return false;
  }
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}
